# version: "3.9"

services:
  frontend:
    container_name: blog_user
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
